Repository micronaut-projects/micronaut-flyway, pull requests merged in 2020-09, with the labels that each got.

#95 [flyway] Update common files for branch 1.2.x
  .github/workflows/release-notes.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: relates-to: build

#94 [flyway] Update common files for branch master
  .github/workflows/release-notes.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: relates-to: build

#100 test: use default classpath:db/migration
  flyway/src/test/groovy/io/micronaut/flyway/FlywayAsyncSpec.groovy
Labels: type: bug

#103 ci: revert to flyway 6.4.4
  gradle.properties
Labels: type: dependency-upgrade

#104 ci: set projectVersion to 2.0.1.BUILD-SNAPSHOT
  gradle.properties
Labels: relates-to: build

#106 ci: set github core branch to 2.1.x
  gradle.properties
Labels: relates-to: build

#107 build: bump up flyway to 6.5.5
  gradle.properties
Labels: relates-to: build

#108 ci: set projectVersion to 2.1.0.BUILD-SNAPSHOT
  gradle.properties
Labels: relates-to: build

#109 fix: onCreated should not return unwrapped datasource
  flyway/src/main/java/io/micronaut/flyway/DataSourceMigrationRunner.java
  flyway/src/test/groovy/io/micronaut/flyway/ApplicationContextSpecification.groovy
  flyway/src/test/groovy/io/micronaut/flyway/ConfigurationFixture.groovy
  flyway/src/test/groovy/io/micronaut/flyway/DataSourceMigrationRunnerSpec.groovy
  flyway/src/test/groovy/io/micronaut/flyway/EventListenerSpec.groovy
Labels: type: bug

#111 Downgrade Flyway to 6.5.4
  flyway/build.gradle
  gradle.properties
Labels: type: dependency-upgrade

#119 [flyway] Update common files for branch master
  .github/workflows/gradle.yml
Labels: relates-to: build

#120 [flyway] Update common files for branch 2.0.x
  .github/workflows/gradle.yml
Labels: relates-to: build
