Repository micronaut-projects/micronaut-flyway, pull requests merged in 2023-04, with the labels that each got.

#375 Refactor GraalVM support and add native testing
  buildSrc/build.gradle
  buildSrc/settings.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.flyway-tests.gradle
  flyway/src/main/java/io/micronaut/flyway/AbstractFlywayMigration.java
  flyway/src/main/java/io/micronaut/flyway/StaticResourceFeature.java
  flyway/src/main/java/io/micronaut/flyway/StaticResourceProvider.java
  flyway/src/main/java/io/micronaut/flyway/graalvm/FeatureDetectorSubstitutions.java
  flyway/src/main/java/io/micronaut/flyway/graalvm/FlywayFeature.java
  flyway/src/main/java/io/micronaut/flyway/graalvm/MicronautPathLocationScanner.java
  flyway/src/main/java/io/micronaut/flyway/graalvm/ScannerSubstitutions.java
  flyway/src/main/resources/META-INF/native-image/io.micronaut.flyway/flyway/native-image.properties
  flyway/src/main/resources/META-INF/native-image/io.micronaut.flyway/micronaut-flyway/native-image.properties
  flyway/src/main/resources/META-INF/native-image/io.micronaut.flyway/micronaut-flyway/reflect-config.json
  flyway/src/main/resources/META-INF/native-image/org.flywaydb/flyway-mysql/native-image.properties
  flyway/src/test/groovy/io/micronaut/flyway/StaticResourceProviderSpec.groovy
  gradle/libs.versions.toml
  settings.gradle
  test-suite-java/build.gradle
  test-suite-java/src/test/java/example/FlywayTest.java
  test-suite-java/src/test/resources/META-INF/native-image/reflect-config.json
  test-suite-java/src/test/resources/application.yml
  test-suite-java/src/test/resources/db/migration/V1__init.sql
  test-suite-java/src/test/resources/db/migration/V2__testdata.sql
  test-suite-java/src/test/resources/db/migration/V3__testdata2.sql
  test-suite-java/src/test/resources/logback.xml
Labels: type: improvement

#359 [flyway] Update common files for branch master
  .gitattributes
  config/checkstyle/checkstyle.xml
  gradle/wrapper/gradle-wrapper.jar
  gradlew
Labels: relates-to: build

#383 M2
  gradle/libs.versions.toml
Labels: type: dependency-upgrade
