Repository micronaut-projects/micronaut-flyway, pull requests merged in 2024-11, with the labels that each got.

#614 [flyway] Update common files for branch 7.5.x
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#612 Flyway to Micronaut Core 4.7
  buildSrc/src/main/groovy/io.micronaut.build.internal.flyway-tests.gradle
  flyway/src/main/resources/META-INF/native-image/io.micronaut.flyway/micronaut-flyway/reflect-config.json
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#617 Flyway endpoint should be serde compatible
  flyway/src/main/java/io/micronaut/flyway/endpoint/FlywayEndpointSerdeImports.java
  settings.gradle
  test-suite-java/build.gradle
  test-suite-serde/build.gradle.kts
  test-suite-serde/src/test/java/io/micronaut/flyway/serde/EndpointSerdeTest.java
  test-suite-serde/src/test/resources/application.properties
  test-suite-serde/src/test/resources/db/migration/V1__init.sql
  test-suite-serde/src/test/resources/logback.xml
Labels: type: bug
